// Minimal Open WebUI client plugin snippet for export button.

export async function registerExportPlugin(app) {
  app.registerTool({
    id: 'session-exporter',
    label: 'Export',
    icon: 'download',
    onClick: async ({ session }) => {
      const token = localStorage.getItem('export_api_key');
      if (!token) {
        alert('Missing export API key');
        return;
      }
      const payload = {
        title: session.title || 'Conversation Export',
        summary: session.summary || 'Generated by Open WebUI.',
        session_id: session.id,
        user_id: session.userId,
        sections: session.sections || [],
        tables: session.tables || [],
        options: {
          template: 'summary_template.docx',
          include_pdf: false,
          include_xlsx: true,
          zip_all: true
        }
      };
      const response = await fetch('/api/v1/export', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify(payload)
      });
      const job = await response.json();
      app.showNotification(`Export job ${job.job_id} queued`);
      let done = false;
      while (!done) {
        await new Promise((resolve) => setTimeout(resolve, 1500));
        const statusResponse = await fetch(`/api/v1/status/${job.job_id}`, {
          headers: { 'Authorization': `Bearer ${token}` }
        });
        const status = await statusResponse.json();
        app.updateNotification(`Export status: ${status.status}`);
        if (status.status === 'complete' && status.result) {
          window.location.href = status.result.download_url;
          done = true;
        }
        if (status.status === 'failed') {
          alert(status.error || 'Export failed');
          done = true;
        }
      }
    }
  });
}
